### PR TITLE
Styles improvement to inventory view

### PR DESCRIPTION
**Pull request by zinkkrysty**
* general styles cleanup

image

### CODE REVIEW

**Comment by guiltygyoza** [comment]
let's create state for highlighting the particular device in the middle panel that is being selected and viewed on the right panel

**Comment by guiltygyoza** [comment]
would also be good to change the hover + highlight color for left panel to creamy blue (maybe #AFEEEE or #AFDBF5) to differentiate from the creamy yellow used for the Deploy Device button on the right.

**Comment by zinkkrysty** [comment]
> would also be good to change the hover + highlight color for left panel to creamy blue (maybe #AFEEEE or #AFDBF5) to differentiate from the creamy yellow used for the Deploy Device button on the right.

I feel like having too many colors in the UI can get confusing and visually messy. I'd rather just stick to one color for highlighting items in a list

**Comment by guiltygyoza** [comment]
> zinkkrysty

I agree with you! let's stick to creamy yellow for consistency.

**Review by guiltygyoza — APPROVED** [review]

**Pull request merged**
